language: python
matrix:
    include:
        - os: linux
          dist: xenial
          python: 3.5
        - os: linux
          dist: xenial
          python: 3.6
        - os: linux
          dist: xenial
          python: 3.7
        - os: osx
          language: generic
          addons:
            homebrew:
              packages: python
          install:
          - python -m pip install -r requirements_osx.txt

before_install:
- python3 -m venv ./venv
- source venv/bin/activate
- python -m pip install coveralls

install:
- sudo apt-get update
- sudo apt-get install -y build-essential python3-dev libdbus-1-dev libdbus-glib-1-dev libgirepository1.0-dev
- python -m pip install -r requirements.txt

script:
- python -m flake8 homekit
- python -m coverage run -m pytest tests/

after_success:
- coveralls
