language: python
matrix:
    include:
        - os: linux
          dist: xenial
          python: 3.5
          env:
            FLAKE8=flake8
            COVERAGE=coverage
            COVERALLS=coveralls
        - os: linux
          dist: xenial
          python: 3.6
          env:
            FLAKE8=flake8
            COVERAGE=coverage
            COVERALLS=coveralls
        - os: linux
          dist: xenial
          python: 3.7
          env:
            FLAKE8=flake8
            COVERAGE=coverage
            COVERALLS=coveralls
        - os: osx
          language: generic
          env:
            PYTHON=3.5.6
            FLAKE8=flake8
            COVERAGE=coverage
            COVERALLS=coveralls
        - os: windows
          language: sh
          env:
            PY=py
            FLAKE8=/c/Python38/Scripts/flake8.exe
            COVERAGE=/c/Python38/Scripts/coverage.exe
            COVERALLS=/c/Python38/Scripts/coveralls.exe

before_install:
    - ./.travis/install.sh
script:
    - ${FLAKE8} homekit
    - ${FLAKE8} tests
    - ${FLAKE8} *.py
    - ${COVERAGE} run -m pytest -s tests/
after_success:
    - ${COVERALLS}
